apiVersion: apps/v1
kind: Deployment
metadata:
  name: silnik
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: silnik
  template:
    metadata:
      labels:
        app: silnik
    spec:
      containers:
        - name: silnik
          image: dariuscore/silnik:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/

---
apiVersion: v1
kind: Service
metadata:
  name: silnik
spec:
  selector: 
    app: silnik
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000